# Generated by Django 5.2.6 on 2025-09-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0002_emailotp2_delete_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('category', models.CharField(max_length=1000)),
                ('veg_nonveg', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cake_image', models.ImageField(blank=True, null=True, upload_to='cakes/')),
            ],
        ),
    ]
