# Generated by Django 5.2.6 on 2025-10-04 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0006_order_city_order_full_name_order_phone_order_zipcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cakeapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cake')),
            ],
        ),
    ]
