# Generated by Django 5.2.6 on 2025-10-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid (COD)'), ('Paid', 'Paid (COD/Online)'), ('Failed', 'Payment Failed'), ('Refunded', 'Refunded')], default='Unpaid', max_length=20),
        ),
    ]
