# Generated by Django 5.2.6 on 2025-10-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0008_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='cake',
        ),
    ]
