# Generated by Django 5.2.6 on 2025-10-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0009_rename_product_orderitem_cake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=200)),
                ('message', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
